services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  orders-service:
    build: ./OrdersService
    container_name: orders-service
    depends_on:
      - rabbitmq

  notification-service:
    build: ./NotificationService
    container_name: notification-service
    depends_on:
      - rabbitmq